spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/gb_shop"
    username: "postgres"
    password: "postgres"
#  security:
#    user:
#      name: 'postgres'
#      password: 'postgres'

